### ISSUE TITLE
Layout problems with text above image preview

### ISSUE THREAD

**Issue by escherba** [Livefyre/StreamHub-iOS-CommentStream-App#103]
User interaction with text above embedded preview during comment creation is somewhat broken. Specifically, the image may occasionally show up above the text, scrolling may sometimes be broken (enabled by typing a few characters), and image preview is automatically shifted down on typing first letter, not on hitting "enter" as expected. 

These issues will be worked on soon.

**Comment by gibron** [comment]
@escherba Hope that you are doing well!
