### ISSUE TITLE
Nested ignored tags are missed by LFSBasicHTMLParser

### ISSUE THREAD

**Issue by samsonjs** [Livefyre/StreamHub-iOS-CommentStream-App#105]
Example:

    <span><strong>some text</strong></span>

will be rendered as:

    <strong>some text</strong>

because the regexes are only run once instead of running until they no longer match.

Possible solutions:

  - unpack each tag matched by the ignored regex, which is a lot of duplication (in LFSBasicHTMLParser)
  - run each regex in a loop as long as it still matches the text (in OHAttributedLabel)

**Comment by gibron** [comment]
Closing this issue as resolved. Please reach out if that status is inaccurate.
