### ISSUE TITLE
Comment sort functionality

### ISSUE THREAD

**Issue by hunterleebrown** [Livefyre/StreamHub-iOS-CommentStream-App#111]
I didn't know where else to leave this question.

Does this app example, or the SDK for iOS, support comment sorting?  

such as:
NEWEST | OLDEST | TOP COMMENTS

**Comment by gibron** [comment]
I believe that this question was answered via email. The answer is that client sorting it is not currently supported in the SDK as it is intended to be a utility to ease data access. With that said, this is functionality that we agree would have great value and is being factored into the roadmap for future versions of the SDK. Please message us through prioritysupport@livefyre.com if the question wasn't answered sufficiently or you would like more info. Thanks!
